#neo4j
server:
    port: 3717

spring:
    redis:
        host: 121.89.234.19
        port: 6397
        database: 0
        timeout: 10000
        expire: 60000
    data:
        neo4j:
            uri: bolt://csubigdata.com:7687
            username: neo4j
            password: csubigdata

dubbo:
    application:
        name: dubbo-consumer
    registry:
        address: zookeeper://localhost:12600?backup=zookeeper://localhost:12500

constants:
    stockType: Stock
    holderType: Holder

mybatis-plus:
    global-config:
        db-config:
            logic-delete-field: delFlag
            logic-delete-value: 1
            logic-not-delete-value: 0
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml
